version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"  
    restart: always
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend
    expose:
      - "5000"  

  frontend:
    build: ./frontend
    expose:
      - "80"    
    restart: always