name: CI
on:
  push:
    [cite_start]branches: [main] # [cite: 216]
jobs:
  test-backend:
    [cite_start]runs-on: ubuntu-latest # [cite: 219]
    steps:
      - [cite_start]uses: actions/checkout@v3 # [cite: 221]
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd backend # Важно зайти в папку [cite: 224]
          pip install -r requirements.txt # [cite: 225]
      - name: Run tests
        run: |
          cd backend # Важно зайти в папку [cite: 228]
          python -m pytest # [cite: 229]
